var MSG = {
  title: "代码",
  blocks: "块",
  linkTooltip: "保存模块并生成链接。",
  runTooltip: "于工作区中运行块所定义的程式。",
  badCode: "程序错误：\n%1",
  timeout: "超过最大执行行数。",
  trashTooltip: "放弃所有块。",
  catLogic: "逻辑",
  catLoops: "循环",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catColour: "颜色",
  catVariables: "变量",
  catFunctions: "函数",
  listVariable: "列表",
  textVariable: "文本",
  httpRequestError: "请求存在问题。",
  linkAlert: "通过这个链接分享您的模块：\n\n%1",
  hashError: "对不起，没有任何已保存的程序对应'%1' 。",
  xmlError: "无法载入您保存的文件。您是否使用其他版本的Blockly创建该文件的？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”以取消您对XML的修改，或选择“取消”以继续编辑XML。",

  /**Toolbox begin*/
  /** toolbox的开始 */
  id_start: "开始",
  /** toolbox的动作 */
  id_actions: "运动",
  /** toolbox的运动 */
  id_moves : "运动",
  /** toolbox的感知 */
  id_sensors : "感知",
  /** toolbox的事件 */
  id_events : "事件",
  /** toolbox的数学 */
  id_math : "数学",
   /** toolbox的控制 */
  id_control : "控制",
  /** toolbox的展示 */
  id_show : "展示",
  /**Toolbox end*/

  /**Start Category begin */
  id_when_start : "点击‘运行’开始",
  id_go_to_start : "重新开始",
  /**Start Category end */
  
  /** Movement Category begin */
  servo_angle_popup_title :"设置舵机旋转角度",
  servo_angle_popup_close:"关闭",
  servo_angle_popup_variable:"变量",
  servo_angle_popup_angle:"角度",
  servo_angle_popup_cancel :"取消",
  servo_angle_popup_ok :"确定",

  rotate_servo_popup_clockwise:"顺时针",
  rotate_servo_popup_anti_clockwise:"逆时针",
  rotate_servo_popup_stop:"停止",
  rotate_servo_popup_title:"设置舵机旋转360度",
  rotate_servo_popup_cancel:"取消",
  rotate_servo_popup_ok:"确定",

  servo_status_popup_title:"设置舵机状态",
  servo_status_popup_cancel:"取消",
  servo_status_popup_ok:"确定",
  servo_status_popup_locking:"锁定",
  servo_status_popup_adjustable:"可调节",
  servo_status_popup_tips:"锁定状态时，不可调节机器人对应的舵机",

  posture_named_popup_title :"保存动作",
  posture_named_popup_cancel :"取消",
  posture_named_popup_ok :"确定",
  posture_named_popup_placeholder :"动作名称",
  posture_named_popup_msg :"动作名称包含非法字符",
  posture_named_too_long : "字数不能超过%1个汉字或%2个字符",

  gyro_rotate_direction_popup_title :"选择陀螺仪旋转方向",
  gyro_rotate_direction_popup_cancel :"取消",
  gyro_rotate_direction_popup_ok :"确定",
  gyro_rotate_direction_popup_curVal :"当前值",
  gyro_rotate_direction_popup_course :"航向角",
  gyro_rotate_direction_popup_horizontal :"横滚角",
  gyro_rotate_direction_popup_house :"俯仰角",

  posture_set_desc : "打开右边开关后可掰动机器人设置动作",
  posture_ok_desc : "摆好动作后可输入动作名称",

  id_servo : '设置舵机',
  id_rotate : '旋转',
  id_degree : '度',
  id_in : '时长',
  id_millsecond : '毫秒',

  id_rotate_circle : '旋转舵机360度',
  id_servos : '旋转舵机',
  id_run_to : '执行',

  id_all: '全部',
  id_lock : '锁定',
  id_unlock : '可调节',

  servo_id : 'ID',
  servo_angle : '角度', 
  movement_gesture: '动作',
  servo_direction : '方向',
  servo_speed : '速度',
  /** Movement Category end */

  /**Control Category begin */
  id_control_wait_for : '等待',
  id_control_repeat : '重复',
  id_control_repeat_times: '次',
  id_control_wait:'等待',
  id_control_seconds:'毫秒',
  id_math_not:'非',
  id_while : '当满足',
  id_until : '直到',
  id_repeat : '重复',
  /**Control Category end */

  /*Event Category begin*/
  maincontrol_box :"控制器",
  low_power :"模型电量低",
  ir_sensor : "红外传感器",
  reflectance : "距离",
  touch_sensor:"触碰传感器",
  status : "状态为",
  title_touch_sensor : "设置触碰传感器",
  click : "单击",
  db_click : "双击",
  press_hold : "长按",
  release : "松开",
  gyroscope : "陀螺仪",
  axie : '轴',
  title_device_tilt : "选择手机/平板状态",
  phone_pad :"手机/平板",
  tilt_left : "向左倾斜",
  tilt_right : "向右倾斜",
  tilt_up : "向上倾斜",
  tilt_down : "向下倾斜",
  tilt_swing : "左右摇晃",
  /*Event Category end*/

  /** Show Category start */
  id_show_play_effect:'播放音效',
  id_show_play_tune:'播放音调',
  id_show_show_emoji:'显示表情',
  id_show_show_LEDs:'显示灯光',
  id_show_time_during:'时长',
  id_show_time_ms:'毫秒',
  id_show_times:'次',
  sound_effects_popup_title :"设置音效",
  sound_effects_popup_cancel :"取消",
  sound_effects_popup_ok :"确定",
  sound_effects_recording_add :"新增录音",
  sound_effects_recording_delete :"删除",
  title_setting_light : "设置灯光",
  title_setting_tune : "设置音调",
  title_setting_emotion : "设置表情",
  id_all_bright: "全亮",
  id_custom: "自定义",
  id_smile: '微笑',
  id_cry : '哭泣',
  id_sad : '伤心',
  id_wink : '眨眼',
  id_dizzy : '晕',
  id_daze : '发呆',
  id_open_eyes : '睁眼',
  close_eyes : '闭眼',
  /** Show Category end */

  /**Sensor Category begin */
  id_sensor_IR_sensor: '红外传感器',
  id_sensor_reflectance_between_obstacle:'与障碍物距离',
  id_sensor_touch_sensor:'触碰传感器',
  id_sensor_touch_sensor_status:'状态',
  id_sensor_gyroscope:'陀螺仪',
  id_sensor_angle:'角度',
  x_axie:'横滚角',
  y_axie:'俯仰角',
  z_axie:'航向角',
  servo:'舵机',
  id_sensor_set_gyroscope:'设置 陀螺仪',
  id_sensor_angle_to_zero:'全部角度为0°',
  /**Sensor Category end */

  /**Math Category begin */
  id_math_variables_set_add : "%1 + %2",
  id_set : "设置",
  id_to : "为",
  /**Math Category end */

  /* Common section begin */
  btn_name_confirm : "确定",
  btn_name_cancel: "取消",
  /* Common section end*/

  
  id_start_info : '运行',
  id_stop_info : '停止',

  title_infrared_sensor : "设置红外传感器",
  current_value: '当前值',

  title_bluetooth_connect : "蓝牙连接",
  title_time_adjust : "设置时长",

  index_back:"返回",
  disconnected : "未连接",

/*项目  begin*/
  //保存项目
  input_rule_msg : "特殊字符无法输入，最多输入%1个字符或%2个汉字",
  variable_inputrule_msg : "不能以数字开头，特殊字符无法输入，最多输入%1个字符或%2个汉字",
  add_project_placeholder : "项目名称",
  project_pop_ok_btn: "确定",
  project_pop_cancel_btn: "取消",
  add_project_pop_title : "保存项目",
  add_project_input_check : "只能输入16个字符",
  project_name_too_long : "字数不超过%1个汉字或%2个字符",
  project_name_popup_msg : "项目名称包含非法字符",
  //是否保存项目
  is_add_project_pop_title :"保存项目",
  is_add_project_pop_tips :"是否保存当前项目",
  //项目列表
  project_list_title :"我的项目",

  //保存项目
  porject_alert_title:"错误",
  porject_alert_tips:"提示",
  porject_alert_content:"对不起，操作对象参数不正确，请检查！",
  porject_alert_content_01:"对不起，你输入的项目名称已经被使用！",
  porject_alert_content_02:"底层业务操作有误，错误信息为：",
  porject_alert_content_03:"底层返回数据有误！",
  porject_alert_content_04:"项目文件读取有误",
  porject_alert_content_05:"对不起，读取的项目文件中含有错误的程序块内容！",
  porject_alert_content_06:"项目保存成功",
  porject_alert_btnText:"确定",
 
  add_recording_ok:"完成",
  recording_tips:"录音中",

  id_control_break : '跳出循环',
  
  id_blue_disconnect : '未连接蓝牙',
  id_ok : '确定',

  recording_title:"录音中",
  recording_cancel:"取消",
  recording_ok:"完成",
  recording_placeholder:"录音名称",
  recording_popup_title:"保存录音",
  recording_name_popup_msg : "录音名称包含非法字符",
 /*项目  end*/
    /*设置音效弹出框音效文件国际化  begin*/
    animal:"动物",
    machine:"机器",
    recording:"录音",
    bear:"熊",
    bird:"鸟",
    chicken:"鸡",
    cow:"牛",
    dog:"狗",
    elephant:"大象",
    giraffe:"长颈鹿",
    horse:"马",
    lion:"狮子",
    monkey:"猴子",
    pig:"猪",
    rhinoceros:"犀牛",
    sealions:"海狮",
    tiger:"老虎",
    walrus:"海象",
    ambulance:"救护车",
    busy_tone:"忙音",
    carhorn:"汽车喇叭",
    carhorn1:"汽车喇叭1",
    doorbell:"门铃",
    engine:"引擎",
    laser:"激光",
    meebot:"小黄人",
    police_car_1:"警车1",
    police_car_2:"警车2",
    ringtones:"来电铃声",
    robot:"机器人",
    telephone_call:"电话呼叫",
    touch_tone:"按键音",
    wave:"电波",

    /*设置音效弹出框音效文件国际化  end*/

 variable_named_popup_placeholder :"变量名",
 title_variable_set : '设置变量',
 variable_named_popup_msg :"以字母或下划线开头，由数字、字母、下划线组成",
 variable_named_too_long : "字数不能超过%1个汉字或%2个字符",
    speed:"速度",
    speed_VS:"非常慢",
    speed_S:"慢速",
    speed_M:"中速",
    speed_V:"快速",/*这个地方跟接口里面没对应上 ，在底下补充一个 */
    speed_F:"快速",
    speed_VF:"非常快",
    speed_no_value:"模型中没有可以360°旋转的舵机",
    speed_only_360_value:"你的积木无角度模式舵机",
    exit_tips:"当前程序未保存，是否继续退出？",
    lights_tips:"当前模型未连接灯光",
    project_has_no_change:"当前程序未改动",
    close_blue:"蓝牙处于连接状态，是否关闭?",
    posture_link:"模型未连接，请先连接模型",
    posture_link_popup_title:"模型连接",
    posture_link_popup_cancel:"取消",
    posture_link_popup_ok:"确定",
    recording_name_repeat:"录音名称已存在",
    recording_named_too_long : "字数不能超过%1个汉字或%2个字符",
    recording_alert_title:"错误提示",
    recording_alert_content:"录音授权失败",
    recording_alert_ok:"确定",
    help_title:"程序块介绍",
    newProjectName:"新项目",
    sysVoiceName:"新录音",
    exit_popup_cancel:"取消",
    exit_popup_ok:"确定",
    exit_popup_title:"提示",
    recording_data_tips:"暂无录音",
    infrared_tips:"当前模型未连接红外传感器",
    touch_tips:"当前模型未连接触碰传感器",
    gyroscope_tips:"当前模型未连接陀螺仪传感器",
    id_infinite_loop_error:"内存即将耗尽，请返回后重试",

    // 新手指引 
    save_project_msg:"保存你的程序点击这里！",
    projectlist_msg:"查看Jimu已学会的程序，并为他建立新程序！",
    swift_msg:"查看swift代码，点击这里！",
    help_msg:"有疑问的时候点击这里！",
    run_msg:"让Jimu按你的程序运动起来！",
    go_skip:"跳过",
    servo_mode_error : '舵机模式错误',
    set_servo_mode : '设置',
    id_show_scenelight:'显示情景灯',
    title_setting_scenelight : "设置情景灯",
    id_happy:"开心",
    id_jingya:"惊讶",    
    id_relei:"热泪盈眶",
    id_leiguang:"泪光闪动",
    id_shangxin:"伤心",
    id_yun:"晕",
    id_fadai:"发呆",
    id_zhayan:"眨眼",
    id_haixiu:"害羞",
    id_shanshuo:"闪烁",
    id_huxi:"呼吸",
    id_fengshan:"风扇",
    id_yugua:"雨刮",

    id_deng:"七彩跑马灯",
    id_disco:"Disco",
    id_caise:"彩色堆叠",
    id_sanyuanse:"三原色",
    select_all:"全选",

    no_common_servo_info : "当前无角度模式舵机（可在一定角度范围内转动），需要设置吗？",
    no_circle_servo_info : "当前无轮模式舵机（可360度旋转），需要设置吗？",
    touch_tips_error : '当前的块ID不正确，请删除后重新设置',
    shumaguan:"数码管",
    show_time:"显示时间",
    show_number:"显示数字",
    show_count:"显示计时",
    stop_count:"停止计时",
    show_countdown:"显示倒计时",
    set_countdown:"设置倒计时",
    let_show_number:"让数码管显示数字",
    let_show_time:"让数码管显示时间",
    let_show_count:"让数码管显示计时",
    let_stop_count:"让数码管停止计时",
    let_show_countdown:"让数码管显示倒计时",
    let_led_scenelight:"让Led灯显示情景灯",
    long_lighton:"长亮",
    no_project_tip:"暂无项目，点击右上角+去创建吧！",
    block_error_info : '当前选中的块编程存在问题，请检查后再试。',





    delay : "延时",
    /*音效--情绪  begin  */
    command:"命令",
    emotion:"情绪",
    transfiguration:"变身",
    happy:"高兴",
    yawn:"哈欠",
    snoring:"呼噜",
    surprise:"惊喜",
    actingcute:"卖萌",
    angry:"生气",
    fail:"失败",
    lose:"失落",
    received:"收到",
    complete:"完成",
    cover:"掩护",
    move:"移动",
    doubt:"疑问",
    nonsense:"呓语",
    emotion_engine:"引擎",
    cheerful:"愉快",
    support:"支援",
    yes:"遵命",
    come_and_play:"歌曲1",
    flexin:"歌曲2",
    london_bridge:"歌曲3",
    yankee_doodle:"歌曲4",
    /*音效--情绪  end  */

    /*------------------新增课程翻译 start-------------------------------------*/
    /*--课程指引翻译--*/
    video_desc:"这是任务说明视频，快快点击查看吧！",
    help_desc:"这里是帮助提示，遇到问题就点击这里吧！",

    /*课程公共翻译 start*/
    course_show:"查看",
    course_hide:"隐藏",
    see_example:"查看示例",
    course_tips:"实在不会时才能查看哦！",
    step_1:"步骤1",
    step_2:"步骤2",
    step_3:"步骤3",
    step_4:"步骤4",
    task:"任务",
    /*课程公共翻译 end*/

    /*------请按照这个规范来命名课程key------*/
    /*----课程2 翻译 start----*/
    course2_title:"唤醒星宝",
    c2_startstory_1:"接下来,为星宝安装程序",
    c2_endstory_1:"哟呵，我回来啦！",
    c2_endstory_2:"星宝，你好！",
    c2_step_page1_1:"任务",
    c2_step_page1_2:"按照正确顺序组合程序块，帮助唤醒星宝：",
    c2_step_page1_3:"1.显示表情：眨眼3次",
    c2_step_page1_4:"2.播放音效（情绪：疑问）",
    c2_step_page1_5:"3.等待5000毫秒",
    c2_step_page2_1:"步骤1",
    c2_step_page2_2:"按顺序组合程序块",
    c2_step_page3_1:"步骤2",
    c2_step_page3_2:"点击\"运行\"程序",
    /*-----课程2 翻译 end-----*/

    /*----课程3 翻译 start----*/
    course3_title:"运动测试",
    c3_startstory_1:"最后，还要测试一下星宝的运动性能",
    c3_endstory_1:"太棒了，星宝的运动能力一切正常!",
    c3_endstory_2:"ok，马上出发吧!",
    c3_step_page1_1:"任务描述",
    c3_step_page1_2:"帮助星宝学会行走的基本运动:",
    c3_step_page1_3:"1.前进",
    c3_step_page1_4:"2.后退",
    c3_step_page1_5:"3.等待2000毫秒",
    c3_step_page1_6:"4.左移",
    c3_step_page1_7:"5.右移",
    c3_step_page2_1:"按顺序组合程序块",
    c3_step_page3_1:"设置等待时间为2000毫秒",
    /*-----课程3 翻译 end-----*/

    /*----课程4 翻译 start----*/
    course4_title:"登录外星",
    c4_startstory_1:"阿尔法星的重力是地球的2/5",
    c4_startstory_2:"赶紧切换到低重力模式登陆",
    c4_endstory_1:"Yoho，成功登陆阿尔法星啦！",
    c4_step_page1_1:"星宝登陆外星，需要切换到低重力模式行走，星宝已经完成待命、抬起右脚、放下右脚、抬起左脚4步，帮助星宝设置最后一步：",
    c4_step_page1_2:"1.放下左脚",
    c4_step_page1_3:"舵机1:0° 舵机2:40° 舵机3:40° 舵机4:0°",
    c4_step_page2_1:"放下左脚",
    c4_step_page2_2:"舵机控制星宝的行走，设置舵机的角度参数，帮助星宝放下左脚：",
    c4_step_page2_3:"1.开启舵机",
    c4_step_page2_4:"2.选择舵机ID",
    c4_step_page2_5:"3.设置舵机逆时针旋转",
    c4_step_page2_6:"4.设置舵机顺时针旋转",
    /*-----课程4 翻译 end-----*/

    /*----课程5 翻译 start----*/
    course5_title:"勇往直前",
    c5_startstory_1:"着陆地点离阿尔法基地还有一段距离",
    c5_startstory_2:"要抓紧时间赶路才行",
    c5_endstory_1:"终于抵达阿尔法基地啦！",
    c5_step_page1_1:"任务",
    c5_step_page1_2:"星宝成功登陆外星，距离基地还有一段距离，帮助星宝向基地进发：",
    c5_step_page1_3:"1.播放音效（情绪：愉快）",
    c5_step_page1_4:"2.重复前进3次",
    c5_step_page2_1:"步骤1",
    c5_step_page2_2:"星宝发出愉快的声音",
    c5_step_page3_1:"步骤2",
    c5_step_page3_2:"重复前进动作3次",
    /*-----课程5 翻译 end-----*/

    /*----课程6 翻译 start----*/
    course6_title:"探索前进",
    c6_startstory_1:"奇怪，为什么阿尔法星基地一片漆黑？",
    c6_startstory_2:"让我用红外探测器查探一下",
    c6_endstory_1:"yoho~成功进入基地内部了！",
    c6_step_page1_1:"任务",
    c6_step_page1_2:"阿尔法基地一片漆黑，帮助星宝在黑暗中躲避障碍，秘密进入基地：",
    c6_step_page1_3:"1.前进",
    c6_step_page1_4:"2.重新开始",
    c6_step_page1_5:"1.红外传感器与障碍物距离小于10",
    c6_step_page1_6:"2.待命",
    c6_step_page1_7:"3.右移",
    c6_step_page1_8:"4.前进",
    c6_step_page1_9:"5.重新开始",
    c6_step_page2_1:"星宝如何检测障碍物？",
    c6_step_page2_2:"1.星宝装备有红外传感器",
    c6_step_page2_3:"2.红外传感器能够检测障碍物",
    c6_step_page2_4:"a.发射器发出红外光",
    c6_step_page2_5:"b.红外光遇到物体时产生反射",
    c6_step_page2_6:"c.接收器接收反射回来的红外光",
    c6_step_page2_7:"d.根据光线强度得出距离",
    c6_step_page2_8:"3.检测距离",
    c6_step_page2_9:"4.检测规律",
    c6_step_page2_10:"a.物体距离越近，反射光照越强",
    c6_step_page2_11:"b.物体的颜色越浅，反射光越强",
    c6_step_page3_1:"红外传感器程序块1",
    c6_step_page3_2:"只要满足红外传感器判断条件，将立即执行条件下的程序块",
    c6_step_page3_3:"1.选择红外ID",
    c6_step_page3_4:"2.设置判断条件",
    c6_step_page3_5:"3.设置判断距离",
    c6_step_page4_1:"步骤1",
    c6_step_page4_2:"星宝重复前进",
    c6_step_page4_3:"回到程序起点，重新执行程序块",
    c6_step_page5_1:"步骤2",
    c6_step_page5_2:"星宝躲避障碍物",
    c6_step_page5_3:"1.设置红外传感器与障碍物距离小于10",
    c6_step_page5_4:"2.星宝执行躲避动作后继续前进",
    c6_step_page6_1:"步骤3",
    c6_step_page6_2:"星宝继续前进",
    c6_step_page6_3:"回到程序起点，重新执行程序块",

    /*-----课程6 翻译 end-----*/

    /*----课程7 翻译 start----*/
    course7_title:"发送信号",
    c7_startstory_1:"天呐，这是路宝的零件！",
    c7_startstory_2:"路宝一定遇到了危险！",
    c7_startstory_3:"先将这里的情况报告给Jimu星球总部！",
    c7_startstory_4:"马上发送无线电信号！",
    c7_endstory_1:"OK，成功发送信号！",
    c7_step_page1_1:"任务",
    c7_step_page1_2:"星宝抵达基地，迅速向总部发送无线电信号：",
    c7_step_page1_3:"1.待命",
    c7_step_page1_4:"2.重复发送以下信号3次",
    c7_step_page1_5:"橙色信号1000毫秒",
    c7_step_page1_6:"等待1000毫秒",
    c7_step_page1_7:"红色信号2000毫秒",
    c7_step_page1_8:"等待2000毫秒",    
    c7_step_page1_9:"绿色信号1000毫秒",
    c7_step_page1_10:"等待1000毫秒",
    c7_step_page2_1:"星宝如何发送信号？",
    c7_step_page2_2:"使用“显示灯光”程序块",
    c7_step_page2_3:"1.设置灯光颜色",
    c7_step_page2_4:"2.选择颜色",
    c7_step_page2_5:"3.勾选全选，双眼将同时启动",
    c7_step_page2_6:"4.设置显示灯光的时长",
    c7_step_page3_1:"步骤1",
    c7_step_page3_2:"星宝待命",
    c7_step_page4_1:"步骤2",
    c7_step_page4_2:"重复发送信号3次",
    c7_step_page5_1:"步骤3",
    c7_step_page5_2:"设置信号",
    c7_step_page5_3:"1.星宝发送橙色信号1000毫秒，等待1000毫秒",
    c7_step_page5_4:"2.继续发送红色信号2000毫秒，等待2000毫秒",
    c7_step_page5_5:"3.再次发送绿色信号1000毫秒，等待1000毫秒",
    /*-----课程7 翻译 end-----*/

    /*----课程8 翻译 start----*/
    course8_title:"寻找线索",
    c8_startstory_1:"一定还有别的线索",
    c8_startstory_2:"我需要找到其他线索救回路宝",
    c8_endstory_1:"太好了！我找到了路宝的搭建图纸！",
    c8_step_page1_1:"任务",
    c8_step_page1_2:"星宝在基地发现了路宝的残骸，决定寻找线索救回路宝：",
    c8_step_page1_3:"1.重复前进，直到红外传感器与障碍物距离小于10",
    c8_step_page1_4:"2.播放音效（情绪:高兴）",
    c8_step_page1_5:"3.显示开心的表情3次",
    c8_step_page1_6:"4.扭动",
    c8_step_page2_1:"红外传感器程序块应用2",
    c8_step_page2_2:"获取红外传感器的判断结果",
    c8_step_page2_3:"1.如果红外传感器返回的数值满足你设置的判断条件，判断结果为真",
    c8_step_page2_4:"2.如果红外传感器返回的数值不满足你设置的判断条件，判断结果为假",
    c8_step_page3_1:"步骤1",
    c8_step_page3_2:"重复前进直到发现线索",
    c8_step_page3_3:"星宝重复前进，直到红外事件成立",
    c8_step_page4_1:"步骤2",
    c8_step_page4_2:"设置红外传感器检测距离小于10",
    c8_step_page5_1:"步骤3",
    c8_step_page5_2:"星宝发现线索，高兴开心的扭动身体",
    c8_step_page6_1:"查看示例",
    c8_step_page6_2:"实在不会时才能查看哦！",
    c8_step_page6_3:"查看",
    c8_step_page6_4:"隐藏",
    /*-----课程8 翻译 end-----*/

    /*----课程10 翻译 start----*/
	  course10_title:"雷达探测",
    c10_startstory_1:"路宝，到底发生了什么？",
    c10_startstory_2:"我们遭到了不明星球异族的袭击，",
    c10_startstory_3:"探星1号被捉走啦！",
    c10_startstory_4:"快使用雷达探测器寻找探星1号的位置吧！",
    c10_startstory_5:"好的！",
    c10_endstory_1:"发现探星1号最后出现的位置了！",
    c10_endstory_2:"厉害了！我的路宝。",
    c10_step_page_1:"探星1号被不明星球异族抓走，帮助路宝使用雷达探测器寻找探星1号的位置：",
    c10_step_page_2:"1.播放音效（机械:忙音）",
    c10_step_page_3:"2.重复转动雷达（舵机5）3次",
    c10_step_page_4:"先转动到40°，时长400毫秒",
    c10_step_page_5:"再转动到-50°，时长400毫秒",
    c10_step_page_6:"路宝雷达",
    c10_step_page_7:"通过设置舵机5来控制雷达的转动",
    c10_step_page_8:"将音效设置为“忙音”",
    c10_step_page_9:"重复转动雷达3次",
    c10_step_page_10:"控制雷达转动范围",
    c10_step_page_11:"设置音效",
    c10_step_page_12:"1.雷达转动到40°",
    c10_step_page_13:"2.雷达转动到－50°",
    /*-----课程10 翻译 end-----*/
    /*----课程11 翻译 start----*/
    course11_title:"前进后退",
    c11_startstory_1:"我们赶紧出发去解救探星1号吧！",
    c11_startstory_2:"好的，全速前进！",
    c11_startstory_3:"坏了，我的运动程序出了问题。",
    c11_startstory_4:"我来帮你修复吧！",
    c11_endstory_1:"我能跑了!",
    c11_endstory_2:"星宝,你真棒!",
    c11_endstory_3:"哈哈，机智如我！",
    c11_step_page_a:"路宝运动能力受到创伤，帮助路宝前进后退：",
    c11_step_page_0:"1.中速(M)前进。",
    c11_step_page_1:"舵机1:+M 舵机2:-M 舵机3:+M 舵机4:-M",
    c11_step_page_2:"2.等待2000毫秒。",
    c11_step_page_3:"3.中速(M)后退。",
    c11_step_page_4:"舵机1:-M 舵机2:+M 舵机3:-M 舵机4:+M",
    c11_step_page_5:"4.等待3000毫秒",
    c11_step_page_6:"路宝轮子",
    c11_step_page_7:"路宝的移动通过舵机的转动来实现",
    c11_step_page_8:"1.右前轮（舵机1）",
    c11_step_page_9:"2.左前轮（舵机2）",
    c11_step_page_10:"3.右后轮（舵机3）",
    c11_step_page_11:"4.左后轮（舵机4）",
    c11_step_page_12:"路宝如何前进、后退？",
    c11_step_page_13:"1.轮子以相同的速度向前转动，路宝前进。",
    c11_step_page_14:"2.轮子以相同的速度向后转动，路宝后退。",
    c11_step_page_15:"3.使用旋转舵机360度程序块控制舵机旋转方向与速度。",
    c11_step_page_16:"路宝前进",
    c11_step_page_17:"1.路宝以中速（M）前进。",
    c11_step_page_18:"2.设置前进时长为2000毫秒",
    c11_step_page_19:"路宝后退",
    c11_step_page_20:"1.路宝以中速（M）后退.",
    c11_step_page_21:"2.设置后退时长为3000毫秒。",
    /*-----课程11 翻译 end-----*/

    /*----课程12 翻译 start----*/
    course12_title:"左转右转",
    c12_startstory_1:"前面有段连续弯道",
    c12_startstory_2:"别慌，看我的！",
    c12_endstory_1:"嘿嘿~通过弯道！",
    c12_endstory_2:"还不赖嘛！",
    c12_step_page1_1:"任务",
    c12_step_page1_2:"前往拯救探星1号的路途中遭遇连续弯道，帮助路宝左转右转:",
    c12_step_page1_3:"1.中速(M)前进",
    c12_step_page1_4:"舵机1:+M 舵机2:-M 舵机3:+M 舵机4:-M",
    c12_step_page1_5:"2.等待1000毫秒",
    c12_step_page1_6:"3.左转：左侧轮子最慢速(VS)，右侧轮子最快速(VF)",
    c12_step_page1_7:"舵机1:+VF 舵机2:-VS 舵机3:+VF 舵机4:-VS",
    c12_step_page1_8:"4.等待3000毫秒",
    c12_step_page1_9:"5.右转：左侧轮子最快速(VF)，右侧轮子最慢速(VS)",
    c12_step_page1_10:"舵机1:+VS 舵机2:-VF 舵机3:+VS 舵机4:-VF",
    c12_step_page1_11:"6.等待3000毫秒",
    c12_step_page2_1:"路宝如何左转、右转？",
    c12_step_page2_2:"1.轮子转动方向相同，右侧轮子比左侧转动速度快时，路宝向左侧转弯。",
    c12_step_page2_3:"2.轮子转动方向相同，左侧轮子比右侧转动速度快时，路宝向右侧转弯。",
    c12_step_page3_1:"步骤1",
    c12_step_page3_2:"路宝前进",
    c12_step_page3_3:"1.路宝以中速（M）前进",
    c12_step_page3_4:"2.设置前进时长为1000毫秒",
    c12_step_page4_1:"步骤2",
    c12_step_page4_2:"路宝左转",
    c12_step_page4_3:"1.设置路宝左侧轮子最慢速(VS)、右侧轮子最快速(VF)。",
    c12_step_page4_4:"2.设置前进时长为3000毫秒。",
    c12_step_page5_1:"步骤3",
    c12_step_page5_2:"路宝右转",
    c12_step_page5_3:"1.设置路宝左侧轮子最快速(VF)、右侧轮子最慢速(VS)。",
    c12_step_page5_4:"2.设置前进时长为3000毫秒。"
    /*-----课程12 翻译 end-----*/

    /*------------------新增课程翻译 end-------------------------------------*/
};
